# Generated by Django 5.0 on 2024-01-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.adddoctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slotid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.slot'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.adddoctor'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.adddoctor'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slotid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.slot'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.appointment'),
        ),
        migrations.AlterField(
            model_name='showappointment',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.appointment'),
        ),
    ]
