# Generated by Django 5.0 on 2024-02-04 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_complain_email_alter_contactus_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
