# Generated by Django 5.0 on 2024-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoctor',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
