# Generated by Django 5.0.3 on 2024-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_payment_razorpay_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showappointment',
            name='chat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='showappointment',
            name='prescription',
            field=models.CharField(max_length=1000),
        ),
    ]
